# Generated by Django 5.1.6 on 2025-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kline',
            constraint=models.UniqueConstraint(fields=('symbol', 'start_time', 'interval', 'time'), name='unique_kline'),
        ),
    ]
