# Generated by Django 5.1.6 on 2025-03-19 11:36

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_delete_kline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(default='5m', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_volume', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('taker_buy_base_volume', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('trade_count', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='2 week')),
            ],
        ),
    ]
