# Generated by Django 5.1.6 on 2025-03-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_symbol_kline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kline',
            unique_together={('symbol', 'time')},
        ),
    ]
