# Generated by Django 5.1.6 on 2025-03-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_kline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kline',
            unique_together={('symbol', 'start_time', 'interval')},
        ),
    ]
