# Generated by Django 5.1.6 on 2025-03-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_symbol_kline'),
    ]

    operations = [
        migrations.AddField(
            model_name='kline',
            name='num_of_trades',
            field=models.BigIntegerField(default=0),
        ),
    ]
