# Generated by Django 5.1.6 on 2025-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_kline_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline',
            name='quote_volume',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='kline',
            name='taker_buy_base_volume',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='kline',
            name='taker_buy_quote_volume',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='kline',
            name='trade_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kline',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
