# Generated by Django 5.1.6 on 2025-03-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_kline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurency',
            name='balance',
            field=models.DecimalField(decimal_places=17, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptocurency',
            name='pnl',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=30),
        ),
    ]
