# Generated by Django 5.1.6 on 2025-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_cryptocurency_balance_alter_cryptocurency_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='precision',
            field=models.IntegerField(default=8),
        ),
    ]
