# Generated by Django 5.1.6 on 2025-03-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object id')),
                ('content', models.CharField(blank=True, max_length=999, null=True, verbose_name='content')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is sent')),
                ('event', models.SmallIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted'), (4, 'Trade Executed'), (5, 'Error Occurred')], null=True, verbose_name='event')),
                ('commit_time', models.DateTimeField(auto_now_add=True, verbose_name='commit time')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='send time')),
                ('exception_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='exception id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-commit_time'],
            },
        ),
    ]
