# Generated by Django 5.1.6 on 2025-03-15 19:53

import src.market.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100,
                 unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100,
                 unique=True, verbose_name='slug')),
                ('rank', models.PositiveIntegerField(default=0,
                 help_text='Order of importance', verbose_name='rank')),
            ],
            options={
                'verbose_name': 'crypto category',
                'verbose_name_plural': 'crypto categories',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['rank', 'ticker']},
        ),
        migrations.AddField(
            model_name='symbol',
            name='change_24h',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='symbol',
            name='circ_supply',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='symbol',
            name='coin',
            field=models.CharField(
                null=True, blank=True, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='logo',
            field=models.ImageField(blank=True, default='coins/USDT.png',
                                    null=True, upload_to=src.market.utils.upload_image_file_path),
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_cap',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='symbol',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='symbol',
            name='rank',
            field=models.PositiveIntegerField(
                null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='volume_24h',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='symbol',
            name='categories',
            field=models.ManyToManyField(
                blank=True, to='market.cryptocategory'),
        ),
    ]
