# Generated by Django 5.1.6 on 2025-03-16 06:30

import src.market.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_cryptocategory_alter_symbol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptocategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='logo',
            field=models.ImageField(blank=True, default='coins/XTVCUSDT.svg', null=True, upload_to=src.market.utils.upload_image_file_path),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='pair',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='ticker',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
