# Generated by Django 5.1.6 on 2025-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_cryptocategory_name_alter_cryptocategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='change_24h',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='circ_supply',
            field=models.DecimalField(decimal_places=17, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='market_cap',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='price',
            field=models.DecimalField(decimal_places=17, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='volume_24h',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
