# Generated by Django 5.1.6 on 2025-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_symbol_change_24h_alter_symbol_circ_supply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ('rank', '-active', 'ticker')},
        ),
        migrations.AddField(
            model_name='symbol',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
